### ISSUE TITLE
There was an error - failed to download recovery 

### ISSUE THREAD

**Issue by DEEgao888** [jyoung8607/openpilot#53] opened 2020-12-10 20:46 UTC
I installed the openpilot using the following instructions:

If you need to run the Community port, you MUST install stock openpilot first. If you're at the EON/Comma Two installer prompt and it's asking for a download URL, then use https://volkswagen.opcfork.org/ instead of comma url, install using the normal methods and instructions. Enable developer and SSH in the setting menu. Then, connect via SSH and run the following command:

cd /data && mv openpilot backup-openpilot && git clone https://github.com/jyoung8607/openpilot.git -b release2 && reboot

After I get everything done, it shows "There was an error - failed to download recovery." and reboot doesn't help. 

I might need downgrade to NEOS 14? Anyone can help? Thanks.

**Comment by jyoung8607** [comment] 2021-06-05 23:19
Duplicate of #51, and fixed.

**Closed by jyoung8607** 2021-06-05 23:19 UTC
